[package]
name = "in-one-weekend"
version = "0.1.0"
authors = ["Ian Mobley <ianmobley@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
rayon = "1.5.1"
common = { path = "../common" }
